/* Отправка формы */
$(".order-form").on("submit",function(e){e.stopPropagation(),e.preventDefault();let o=this,r=($(".submit",o),new FormData);return $('[name="hidden"]',o).val()?o.reset():$.get("https://ipinfo.io",function(e){if("UA"!==e.country)return alert("Форма може бути заповнена тільки з України. Або Вимкніть VPN."),o.reset(),!1;$(".submit",o).val("Відправлення..."),$("input,textarea",o).attr("disabled","");var e=$('[name="name"]',o).val(),t=$('[name="phone"]',o).val(),a=$('[name="email"]',o).val(),n=$('[name="select"]',o).val();e&&r.append("Ім`я",e),t&&r.append("Телефон",t),a&&r.append("Email",a),n&&r.append("Пропозиція",n),r.append("Товар",window.location.href),$.ajax({url:"telegram.php",type:"POST",data:r,cache:!1,dataType:"json",processData:!1,contentType:!1,xhr:function(){var e=$.ajaxSettings.xhr();return e.upload&&e.upload.addEventListener("progress",function(t){if(t.lengthComputable){let e=t.loaded/t.total*100;e=e.toFixed(0),$(".submit",o).html(e+"%")}},!1),e},error:function(e,t){},complete:function(){window.location.href="/thank-you-page",o.reset()}})},"json"),!1});

/* Devtools */
document.addEventListener("keydown",(e=>{const t=e.ctrlKey||e.metaKey&&e.shiftKey;t&&["I","J","C"].includes(e.key)&&e.preventDefault(),(t||e.ctrlKey||e.metaKey)&&"S"===e.key&&e.preventDefault(),"F12"===e.key&&"F12"===e.code&&e.preventDefault()}));

/* Маска на номер телефона */
document.addEventListener("DOMContentLoaded",(function(){document.querySelectorAll('[name="phone"]').forEach((function(e){let t,n="";function l(e){e.keyCode&&(t=e.keyCode),this.selectionStart<3&&e.preventDefault();let l="+38 (___) ___-__-__",i=0,c=l.replace(/\D/g,""),s=this.value.replace(/\D/g,""),u=l.replace(/[_\d]/g,(function(e){return i<s.length?s.charAt(i++)||c.charAt(i):e}));i=u.indexOf("_"),-1!=i&&(i<5&&(i=3),u=u.slice(0,i));let r=l.substr(0,this.value.length).replace(/_+/g,(function(e){return"\\d{1,"+e.length+"}"})).replace(/[+()]/g,"\\$&");r=new RegExp("^"+r+"$"),(!r.test(this.value)||this.value.length<5||t>47&&t<58)&&(this.value=u,a(this,this.value.length)),n=this.value}function a(e,t){if(null!==e)if(e.createTextRange){let n=e.createTextRange();n.move("character",t),n.select()}else e.selectionStart?(e.focus(),e.setSelectionRange(t,t)):e.focus()}e.addEventListener("focus",(function(){a(this,this.value.length)})),e.addEventListener("input",l,!1),e.addEventListener("focus",l,!1),e.addEventListener("blur",(function(e){this.value===n&&document.activeElement!==this&&(this.value=n)})),e.addEventListener("keydown",l,!1)}))}));

/* Плавная прокрутка */
$(document).ready(function(){$('a[href^="#order-form"]').click(function(){var t=$(this).attr("href"),e=$(t).offset().top;return(jQuery("html:not(:animated),body:not(:animated)").animate({scrollTop:e},1000),!1)})})